In [3]:
import sys
import os

current_file_path = os.path.abspath(os.getcwd()) # Funciona solo para JupyterNotebooks

# Obtener la ruta del directorio raíz del proyecto
project_root = os.path.abspath(os.path.join(os.path.dirname(current_file_path)))

# Añadir el directorio raíz del proyecto al sys.path
sys.path.append(project_root)

from config import INPUTS_FOLDER

statement_path = os.path.join(INPUTS_FOLDER, 'test_files', 'BBVA', '2206.pdf')

### Pipeline description

In [4]:
from document_reader import PDFReader
from bank_detector import DefaultBankDetector
import logging
logging.getLogger('pdfminer').setLevel(logging.ERROR) # Abvoid PDFMiner warnings

bank_detector = DefaultBankDetector(PDFReader(statement_path))

extracted_words = bank_detector.get_extracted_words()
extracted_words

AttributeError: 'DefaultBankDetector' object has no attribute 'extracted_words'

In [63]:
bank = bank_detector.detect_bank()
statement_type = bank_detector.detect_statement_type()
statement_properties = bank_detector.get_statement_properties()

print(f'{bank} - {statement_type}')

banamex - credit

In [64]:
from table_boundary_detector import TransactionTableBoundaryDetector

boundary_detector = TransactionTableBoundaryDetector(bank_detector)

start_idx = boundary_detector.start_idx
end_idx = boundary_detector.end_idx

if statement_type == 'credit' and (start_idx is None or end_idx is None):
    print('New format')
    statement_properties = bank_detector.get_statement_properties(new_credit_format= True)
    boundary_detector = TransactionTableBoundaryDetector(extracted_words, statement_properties)
    
    start_idx = boundary_detector.start_idx
    end_idx = boundary_detector.end_idx

df_table = boundary_detector.get_filtered_table_words()

print(f'{start_idx} - {end_idx}')
df_table

252 - 641

     page           text       x0      top       x1   bottom
0       1          Fecha   25.510  476.827   53.900  486.827
1       1  Concepto/Giro   68.027  476.827  136.757  486.827
2       1             de  139.657  476.827  150.647  486.827
3       1        Negocio  153.547  476.827  191.297  486.827
4       1      Población  340.139  476.827  386.069  486.827
..    ...            ...      ...      ...      ...      ...
384     2       PASTERIA   81.635  329.749  123.566  338.749
385     2            QRO  125.897  329.749  144.428  338.749
386     2            CCA  167.738  329.749  185.126  338.749
387     2      230713PY5  187.457  329.749  233.168  338.749
388     2         785.45  528.987  329.749  558.390  338.749

[389 rows x 6 columns]

In [65]:
from row_segmenter import TransactionRowSegmenter

row_segmenter = TransactionRowSegmenter(df_table, bank_detector)

column_delimitation = row_segmenter.delimit_column_positions()
grouped_rows = row_segmenter.group_rows()

print(row_segmenter.row_threshold)
print(column_delimitation)
grouped_rows

6.338000000000001
{'columns': ['Fecha', 'Concepto/Giro de Negocio Mensualidad * / Tipos de Cambio', 'Población / RFC Moneda Ext.', 'Otras Divisas', 'Pesos'], 'x0': [25.51, 68.027, 340.139, 445.016, 529.064], 'x1': [53.900000000000006, 222.69700000000006, 398.65999999999997, 479.716, 557.524]}

,row_group,text,words,top,bottom,page
0,0,Fecha Concepto/Giro de Negocio Población / RFC...,"[(Fecha, 25.51, 53.900000000000006), (Concepto...",476.827,486.827,1
1,1,Moneda Ext. Divisas Mensualidad * / Tipos de C...,"[(Moneda, 340.13, 376.41), (Ext., 379.31, 398....",488.678,498.688,1
2,2,"Jun 10 VIVA AEROBUS CIB ANA050518RL1 1,571.50","[(Jun, 25.51, 40.918), (10, 43.249, 51.835), (...",501.526,510.526,1
3,3,"Jun 10 PAGO INTERBANCARIO 12,151.00-","[(Jun, 25.51, 41.863), (10, 44.473, 56.407), (...",512.864,521.864,1
4,4,Jun 12 AKI SAN ANGELO SSF 830912738 185.00,"[(Jun, 25.51, 40.918), (12, 43.249, 51.1780000...",524.202,533.202,1
5,5,Jun 14 F AHORRO MEGA GARCIA L CFC110121742 126.00,"[(Jun, 25.51, 40.918), (14, 43.249, 51.682), (...",535.540,544.540,1
6,6,Jun 14 BP*REST Y CAFE PLA 120807BK0 603.75,"[(Jun, 25.51, 40.918), (14, 43.249, 51.682), (...",546.878,555.878,1
7,7,"Jun 14 MSFT STORE AME 1404027R0 1,749.00","[(Jun, 25.51, 40.918), (14, 43.249, 51.682), (...",558.216,567.216,1
8,8,Jun 16 STR*UBER EATS UPM 191014S31 7.44,"[(Jun, 25.51, 40.918), (16, 43.249, 51.583), (...",569.554,578.554,1
9,9,"Jun 16 STR*UBER EATS UPM 191014S31 2,148.24","[(Jun, 25.51, 40.918), (16, 43.249, 51.583), (...",580.892,589.892,1
10,10,Jun 16 MERPAGO*HELADOSMAR MAG 2105031W3 312.00,"[(Jun, 25.51, 40.918), (16, 43.249, 51.583), (...",592.230,601.230,1
11,11,Jun 16 STRIPE *UBER EATS UPM 191014S31 64.67,"[(Jun, 25.51, 40.918), (16, 43.249, 51.583), (...",603.568,612.568,1
12,12,Jun 20 TDA O MART 2 MFB 170321TS0 80.00,"[(Jun, 25.51, 40.918), (20, 43.249, 54.148), (...",614.906,623.906,1
13,13,Jun 20 TDA O MART 2 MFB 170321TS0 256.00,"[(Jun, 25.51, 40.918), (20, 43.249, 54.148), (...",626.244,635.244,1
14,14,"Jun 21 NINTENDO CA1225255214 800-2553700 1,897.00","[(Jun, 25.51, 40.918), (21, 43.249, 51.1780000...",637.582,646.582,1
15,15,Jun 21 STRIPE *UBER EATS UPM 191014S31 584.89,"[(Jun, 25.51, 40.918), (21, 43.249, 51.1780000...",648.920,657.920,1
16,16,Jun 22 RAPPI TRA 150604TW1 14.39-,"[(Jun, 25.51, 41.863), (22, 44.473, 56.407), (...",660.258,669.258,1
17,17,"Jun 22 F AHORRO QRSR CENTRO S CFC110121742 1,7...","[(Jun, 25.51, 40.918), (22, 43.249, 53.4910000...",671.596,680.596,1
18,18,Jun 22 RAPPI E COM TRA 150604TW1 295.90,"[(Jun, 25.51, 40.918), (22, 43.249, 53.4910000...",682.934,691.934,1
19,19,Jun 22 ABASTOS ESE 930624B79 882.85,"[(Jun, 25.51, 40.918), (22, 43.249, 53.4910000...",694.272,703.272,1
20,20,Jun 22 RAPPI TRA 150604TW1 14.39,"[(Jun, 25.51, 40.918), (22, 43.249, 53.4910000...",705.610,714.610,1
21,21,Jun 24 GPO FLECHA AMARILLA API 6609273E0 510.00,"[(Jun, 25.51, 40.918), (24, 43.249, 53.9950000...",716.948,725.948,1
22,22,Jun 24 EXTRA K PLAZA POLANCO TEX 9302097F3 71.50,"[(Jun, 25.51, 40.918), (24, 43.249, 53.9950000...",728.286,737.286,1
23,23,Jun 24 LA CASA DE TONO PLAZA GLC 170630IU9 86.00,"[(Jun, 25.51, 40.918), (24, 43.249, 53.9950000...",739.624,748.624,1
24,24,Jun 24 STRIPE *UBER TRIP UPM 200220LK5 20.00,"[(Jun, 25.51, 40.918), (24, 43.249, 53.9950000...",750.962,759.962,1
25,25,Página 1 de 7,"[(Página, 513.451, 541.1080000000001), (1, 543...",775.283,784.283,1
26,26,Centro de Ciudad de México y cualquier,"[(Centro, 303.004, 334.654), (de, 337.35400000...",21.403,32.631,2
27,27,Atención otra ciudad del país: 55 2262 4646,"[(Atención, 306.988, 348.588), (otra, 354.312,...",32.452,42.593,2
28,28,Telefónica www.citibanamex.com,"[(Telefónica, 300.455, 348.585), (www.citibana...",43.502,53.502,2
29,29,Detalle de Operaciones,"[(Detalle, 25.51, 64.726), (de, 67.96600000000...",73.425,85.425,2
30,30,Fecha Concepto/Giro de Negocio Población / RFC...,"[(Fecha, 25.51, 53.900000000000006), (Concepto...",89.627,99.627,2
31,31,Moneda Ext. Divisas Mensualidad * / Tipos de C...,"[(Moneda, 340.13, 376.41), (Ext., 379.31, 398....",101.478,111.488,2
32,32,Jun 24 STRIPE *UBER TRIP UPM 200220LK5 62.22,"[(Jun, 25.51, 40.918), (24, 43.249, 53.9950000...",114.327,123.327,2
33,33,Jun 25 LA CASA DE TONO PLAZA GLC 170630IU9 328.00,"[(Jun, 25.51, 40.918), (25, 43.249, 53.8150000...",125.665,134.665,2
34,34,Jun 27 PAGO MI TELMEX TME 840315KT6 382.00,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",137.003,146.003,2
35,35,Jun 27 D LOCAL*RAPPI TRA 150604TW1 263.35,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",148.341,157.341,2
36,36,Jun 27 STRIPE *UBER TRIP UPM 200220LK5 249.96,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",159.679,168.679,2
37,37,Jun 27 STRIPE *UBER TRIP UPM 200220LK5 15.00,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",171.017,180.017,2
38,38,Jun 27 STRIPE *UBER TRIP UPM 200220LK5 20.00,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",182.355,191.355,2
39,39,Jun 27 STRIPE *UBER TRIP UPM 200220LK5 119.96,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",193.693,202.693,2
40,40,Jun 27 CAFEBRERIA EL PENDULO CIUDAD DE MEX 655.50,"[(Jun, 25.51, 40.918), (27, 43.249, 53.374), (...",205.031,214.031,2
41,41,Jun 28 PRIMERA PLUS RES 130904JH8 247.75,"[(Jun, 25.51, 40.918), (28, 43.249, 54.0940000...",216.369,225.369,2
42,42,Jun 28 STRIPE *UBER TRIP UPM 200220LK5 20.00,"[(Jun, 25.51, 40.918), (28, 43.249, 54.0940000...",227.707,236.707,2
43,43,Jun 28 STRIPE *UBER TRIP UPM 200220LK5 399.99,"[(Jun, 25.51, 40.918), (28, 43.249, 54.0940000...",239.045,248.045,2
44,44,Jun 29 BP*ALITAS PLAZAESFERA GRE 111107FZ2 307.20,"[(Jun, 25.51, 40.918), (29, 43.249, 53.896), (...",250.383,259.383,2
45,45,"Jun 29 GAS NOEL LOS ANGELES DGN 811026BU6 1,12...","[(Jun, 25.51, 40.918), (29, 43.249, 53.896), (...",261.721,270.721,2
46,46,Jun 29 TELCEL VPS 100716CK9 200.00,"[(Jun, 25.51, 40.918), (29, 43.249, 53.896), (...",273.059,282.059,2
47,47,Jun 30 F AHORRO QRCA CAMPEST CFC110121742 244.00,"[(Jun, 25.51, 40.918), (30, 43.249, 54.094), (...",284.397,293.397,2
48,48,"Jun 30 COSTCO QUERETARO CME910715UB9 5,759.30","[(Jun, 25.51, 40.918), (30, 43.249, 54.094), (...",295.735,304.735,2
49,49,"Jun 30 COSTCO QUERETARO CME910715UB9 3,529.20","[(Jun, 25.51, 40.918), (30, 43.249, 54.094), (...",307.073,316.073,2
50,50,Jul 4 F AHORRO QRHU HUIMILP CFC110121742 229.00,"[(Jul, 25.51, 38.074), (4, 42.736000000000004,...",318.411,327.411,2
51,51,Jul 4 LA PASTERIA QRO CCA 230713PY5 785.45,"[(Jul, 25.51, 38.074), (4, 42.736000000000004,...",329.749,338.749,2

In [66]:
from table_reconstructor import TransactionTableReconstructor

table_reconstructor = TransactionTableReconstructor(grouped_rows, column_delimitation, bank_detector)

table_reconstructor.get_structured_table()

,Fecha,Concepto/Giro de Negocio Mensualidad * / Tipos de Cambio,Población / RFC Moneda Ext.,Otras Divisas,Pesos
0,Fecha,Concepto/Giro de Negocio Pesos,Población / RFC,Otras,
1,,Mensualidad * / Tipos de Cambio,Moneda Ext.,Divisas,
2,Jun 10,VIVA AEROBUS CIB ANA050518RL1,,,"1,571.50"
3,Jun 10,PAGO INTERBANCARIO,,,"12,151.00-"
4,Jun 12,AKI SAN ANGELO SSF 830912738,,,185.00
5,Jun 14,F AHORRO MEGA GARCIA L CFC110121742,,,126.00
6,Jun 14,BP*REST Y CAFE PLA 120807BK0,,,603.75
7,Jun 14,MSFT STORE AME 1404027R0,,,"1,749.00"
8,Jun 16,STR*UBER EATS UPM 191014S31,,,7.44
9,Jun 16,STR*UBER EATS UPM 191014S31,,,"2,148.24"
10,Jun 16,MERPAGO*HELADOSMAR MAG 2105031W3,,,312.00
11,Jun 16,STRIPE *UBER EATS UPM 191014S31,,,64.67
12,Jun 20,TDA O MART 2 MFB 170321TS0,,,80.00
13,Jun 20,TDA O MART 2 MFB 170321TS0,,,256.00
14,Jun 21,NINTENDO CA1225255214 800-2553700,,,"1,897.00"
15,Jun 21,STRIPE *UBER EATS UPM 191014S31,,,584.89
16,Jun 22,RAPPI TRA 150604TW1,,,14.39-
17,Jun 22,F AHORRO QRSR CENTRO S CFC110121742,,,"1,764.00"
18,Jun 22,RAPPI E COM TRA 150604TW1,,,295.90
19,Jun 22,ABASTOS ESE 930624B79,,,882.85
20,Jun 22,RAPPI TRA 150604TW1,,,14.39
21,Jun 24,GPO FLECHA AMARILLA API 6609273E0,,,510.00
22,Jun 24,EXTRA K PLAZA POLANCO TEX 9302097F3,,,71.50
23,Jun 24,LA CASA DE TONO PLAZA GLC 170630IU9,,,86.00
24,Jun 24,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
25,,Página 1 de 7,,,
26,,Centro,de Ciudad de México,,
27,,Atención,otra ciudad,55 2262 4646,
28,,Telefónica,www.citibanamex.com,,
29,Detalle,de Operaciones,,,
30,Fecha,Concepto/Giro de Negocio Pesos,Población / RFC,Otras,
31,,Mensualidad * / Tipos de Cambio,Moneda Ext.,Divisas,
32,Jun 24,STRIPE *UBER TRIP UPM 200220LK5,,,62.22
33,Jun 25,LA CASA DE TONO PLAZA GLC 170630IU9,,,328.00
34,Jun 27,PAGO MI TELMEX TME 840315KT6,,,382.00
35,Jun 27,D LOCAL*RAPPI TRA 150604TW1,,,263.35
36,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,249.96
37,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,15.00
38,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
39,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,119.96
40,Jun 27,CAFEBRERIA EL PENDULO CIUDAD DE MEX,,,655.50
41,Jun 28,PRIMERA PLUS RES 130904JH8,,,247.75
42,Jun 28,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
43,Jun 28,STRIPE *UBER TRIP UPM 200220LK5,,,399.99
44,Jun 29,BP*ALITAS PLAZAESFERA GRE 111107FZ2,,,307.20
45,Jun 29,GAS NOEL LOS ANGELES DGN 811026BU6,,,"1,124.00"
46,Jun 29,TELCEL VPS 100716CK9,,,200.00
47,Jun 30,F AHORRO QRCA CAMPEST CFC110121742,,,244.00
48,Jun 30,COSTCO QUERETARO CME910715UB9,,,"5,759.30"
49,Jun 30,COSTCO QUERETARO CME910715UB9,,,"3,529.20"
50,Jul 4,F AHORRO QRHU HUIMILP CFC110121742,,,229.00
51,Jul 4,LA PASTERIA QRO CCA 230713PY5,,,785.45

In [67]:
df_structured = table_reconstructor.reconstruct_table()
df_structured

,Fecha,Concepto/Giro de Negocio Mensualidad * / Tipos de Cambio,Población / RFC Moneda Ext.,Otras Divisas,Pesos
0,Jun 10,VIVA AEROBUS CIB ANA050518RL1,,,"1,571.50"
1,Jun 10,PAGO INTERBANCARIO,,,"12,151.00-"
2,Jun 12,AKI SAN ANGELO SSF 830912738,,,185.00
3,Jun 14,F AHORRO MEGA GARCIA L CFC110121742,,,126.00
4,Jun 14,BP*REST Y CAFE PLA 120807BK0,,,603.75
5,Jun 14,MSFT STORE AME 1404027R0,,,"1,749.00"
6,Jun 16,STR*UBER EATS UPM 191014S31,,,7.44
7,Jun 16,STR*UBER EATS UPM 191014S31,,,"2,148.24"
8,Jun 16,MERPAGO*HELADOSMAR MAG 2105031W3,,,312.00
9,Jun 16,STRIPE *UBER EATS UPM 191014S31,,,64.67
10,Jun 20,TDA O MART 2 MFB 170321TS0,,,80.00
11,Jun 20,TDA O MART 2 MFB 170321TS0,,,256.00
12,Jun 21,NINTENDO CA1225255214 800-2553700,,,"1,897.00"
13,Jun 21,STRIPE *UBER EATS UPM 191014S31,,,584.89
14,Jun 22,RAPPI TRA 150604TW1,,,14.39-
15,Jun 22,F AHORRO QRSR CENTRO S CFC110121742,,,"1,764.00"
16,Jun 22,RAPPI E COM TRA 150604TW1,,,295.90
17,Jun 22,ABASTOS ESE 930624B79,,,882.85
18,Jun 22,RAPPI TRA 150604TW1,,,14.39
19,Jun 24,GPO FLECHA AMARILLA API 6609273E0,,,510.00
20,Jun 24,EXTRA K PLAZA POLANCO TEX 9302097F3,,,71.50
21,Jun 24,LA CASA DE TONO PLAZA GLC 170630IU9,,,86.00
22,Jun 24,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
23,Jun 24,STRIPE *UBER TRIP UPM 200220LK5,,,62.22
24,Jun 25,LA CASA DE TONO PLAZA GLC 170630IU9,,,328.00
25,Jun 27,PAGO MI TELMEX TME 840315KT6,,,382.00
26,Jun 27,D LOCAL*RAPPI TRA 150604TW1,,,263.35
27,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,249.96
28,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,15.00
29,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
30,Jun 27,STRIPE *UBER TRIP UPM 200220LK5,,,119.96
31,Jun 27,CAFEBRERIA EL PENDULO CIUDAD DE MEX,,,655.50
32,Jun 28,PRIMERA PLUS RES 130904JH8,,,247.75
33,Jun 28,STRIPE *UBER TRIP UPM 200220LK5,,,20.00
34,Jun 28,STRIPE *UBER TRIP UPM 200220LK5,,,399.99
35,Jun 29,BP*ALITAS PLAZAESFERA GRE 111107FZ2,,,307.20
36,Jun 29,GAS NOEL LOS ANGELES DGN 811026BU6,,,"1,124.00"
37,Jun 29,TELCEL VPS 100716CK9,,,200.00
38,Jun 30,F AHORRO QRCA CAMPEST CFC110121742,,,244.00
39,Jun 30,COSTCO QUERETARO CME910715UB9,,,"5,759.30"
40,Jun 30,COSTCO QUERETARO CME910715UB9,,,"3,529.20"

In [68]:
from table_normalizer import TransactionTableNormalizer

normalizer = TransactionTableNormalizer(df_structured, bank_detector)

df_normalized = normalizer.normalize_table()
df_normalized

         Date                          Description    Amount   Type
0  2024-06-10        VIVA AEROBUS CIB ANA050518RL1  -1571.50  Cargo
1  2024-06-10                   PAGO INTERBANCARIO  12151.00  Abono
2  2024-06-12         AKI SAN ANGELO SSF 830912738   -185.00  Cargo
3  2024-06-14  F AHORRO MEGA GARCIA L CFC110121742   -126.00  Cargo
4  2024-06-14         BP*REST Y CAFE PLA 120807BK0   -603.75  Cargo
5  2024-06-14             MSFT STORE AME 1404027R0  -1749.00  Cargo
6  2024-06-16          STR*UBER EATS UPM 191014S31     -7.44  Cargo
7  2024-06-16          STR*UBER EATS UPM 191014S31  -2148.24  Cargo
8  2024-06-16     MERPAGO*HELADOSMAR MAG 2105031W3   -312.00  Cargo
9  2024-06-16      STRIPE *UBER EATS UPM 191014S31    -64.67  Cargo
10 2024-06-20           TDA O MART 2 MFB 170321TS0    -80.00  Cargo
11 2024-06-20           TDA O MART 2 MFB 170321TS0   -256.00  Cargo
12 2024-06-21    NINTENDO CA1225255214 800-2553700  -1897.00  Cargo
13 2024-06-21      STRIPE *UBER EATS UPM 191014S31   -584.89  Cargo
14 2024-06-22                  RAPPI TRA 150604TW1     14.39  Abono
15 2024-06-22  F AHORRO QRSR CENTRO S CFC110121742  -1764.00  Cargo
16 2024-06-22            RAPPI E COM TRA 150604TW1   -295.90  Cargo
17 2024-06-22                ABASTOS ESE 930624B79   -882.85  Cargo
18 2024-06-22                  RAPPI TRA 150604TW1    -14.39  Cargo
19 2024-06-24    GPO FLECHA AMARILLA API 6609273E0   -510.00  Cargo
20 2024-06-24  EXTRA K PLAZA POLANCO TEX 9302097F3    -71.50  Cargo
21 2024-06-24  LA CASA DE TONO PLAZA GLC 170630IU9    -86.00  Cargo
22 2024-06-24      STRIPE *UBER TRIP UPM 200220LK5    -20.00  Cargo
23 2024-06-24      STRIPE *UBER TRIP UPM 200220LK5    -62.22  Cargo
24 2024-06-25  LA CASA DE TONO PLAZA GLC 170630IU9   -328.00  Cargo
25 2024-06-27         PAGO MI TELMEX TME 840315KT6   -382.00  Cargo
26 2024-06-27          D LOCAL*RAPPI TRA 150604TW1   -263.35  Cargo
27 2024-06-27      STRIPE *UBER TRIP UPM 200220LK5   -249.96  Cargo
28 2024-06-27      STRIPE *UBER TRIP UPM 200220LK5    -15.00  Cargo
29 2024-06-27      STRIPE *UBER TRIP UPM 200220LK5    -20.00  Cargo
30 2024-06-27      STRIPE *UBER TRIP UPM 200220LK5   -119.96  Cargo
31 2024-06-27  CAFEBRERIA EL PENDULO CIUDAD DE MEX   -655.50  Cargo
32 2024-06-28           PRIMERA PLUS RES 130904JH8   -247.75  Cargo
33 2024-06-28      STRIPE *UBER TRIP UPM 200220LK5    -20.00  Cargo
34 2024-06-28      STRIPE *UBER TRIP UPM 200220LK5   -399.99  Cargo
35 2024-06-29  BP*ALITAS PLAZAESFERA GRE 111107FZ2   -307.20  Cargo
36 2024-06-29   GAS NOEL LOS ANGELES DGN 811026BU6  -1124.00  Cargo
37 2024-06-29                 TELCEL VPS 100716CK9   -200.00  Cargo
38 2024-06-30   F AHORRO QRCA CAMPEST CFC110121742   -244.00  Cargo
39 2024-06-30        COSTCO QUERETARO CME910715UB9  -5759.30  Cargo
40 2024-06-30        COSTCO QUERETARO CME910715UB9  -3529.20  Cargo

In [69]:
normalizer.period_idx

51

In [70]:
from data_exporter import CsvExporter
from config import OUTPUTS_FOLDER

exporter = CsvExporter(df_normalized)
file_path = os.path.join(OUTPUTS_FOLDER, bank, f'{bank}_{statement_type}.csv')

exporter.export_to_csv(file_path)

Data exported to c:\Users\mario\Proyectos\Aether\Aether_v1\documents\outputs\banamex\banamex_credit.csv successfully.