In [31]:
import sys
import os

current_file_path = os.path.abspath(os.getcwd()) # Funciona solo para JupyterNotebooks
# Obtener la ruta del directorio raíz del proyecto
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(current_file_path)))
# Añadir el directorio raíz del proyecto al sys.path
sys.path.append(PROJECT_ROOT)

INPUTS_FOLDER = os.path.join(PROJECT_ROOT, 'tests', 'test_data', 'inputs')
OUTPUTS_FOLDER = os.path.join(PROJECT_ROOT, 'tests', 'test_data', 'outputs')

def get_file_from_path(file_path: str) -> str:
    return os.path.join(INPUTS_FOLDER, file_path)

test_files = [
    'banorte_credit_new.pdf',
    'banorte_credit_old.pdf',
    'banorte_debit.pdf',
    'bbva_debit.pdf',
]

file_path = get_file_from_path('banorte_debit.pdf')

In [32]:
from models import DocumentProcessingFacade
import logging
logging.getLogger('pdfminer').setLevel(logging.ERROR) # Abvoid PDFMiner warnings

doc_processor = DocumentProcessingFacade(file_path)
statement_properties = doc_processor.get_statement_properties()
bank = statement_properties['bank']
statement_type = statement_properties['statement_type']
new_format = statement_properties['new_format']

print(bank, ' - ', statement_type, ' - ', new_format)

banorte  -  debit  -  None

In [33]:
extracted_words = doc_processor.get_extracted_words()

if statement_type == 'debit':
    extracted_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_extracted_words.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    extracted_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_extracted_words.csv')
    
extracted_words.to_csv(extracted_words_path, index=False)

In [34]:
corrected_extracted_words = doc_processor.get_corrected_extracted_words()
corrected_extracted_words

      page          text          x0        top          x1    bottom
0        1         MARIA   48.816000   51.69000   67.446000   60.6900
1        1      FERNANDA   68.859000   51.69000   98.856000   60.6900
2        1       CANUDAS  100.269000   51.69000  126.882000   60.6900
3        1      ZERTUCHE  128.295000   51.69000  156.294000   60.6900
4        1         CALLE   48.816000   59.40000   65.520000   68.4000
...    ...           ...         ...        ...         ...       ...
1853     6           6/6  557.280000  764.60400  566.739000  773.6040
1854     6         Nuevo   50.400000  772.49955   69.216588  780.4998
1855     6         Leon.   70.688634  772.49955   86.553130  780.4998
1856     6           RFC   88.025176  772.49955   99.017519  780.4998
1857     6  BMN930209927  100.489565  772.49955  147.043020  780.4998

[1858 rows x 6 columns]

In [35]:
if statement_type == 'debit':
    corrected_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_corrected_words.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    corrected_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_corrected_words.csv')
    
corrected_extracted_words.to_csv(corrected_words_path, index=False)

In [36]:
from models import TableProcessingFacade

table_processor = TableProcessingFacade(corrected_extracted_words, statement_properties)
reconstructor = table_processor.get_reconstructor()
structured_table = reconstructor.get_structured_table()
structured_table

,Date,Description,MONTO DEL DEPOSITO,MONTO DEL RETIRO,SALDO
0,None,Cuenta Enlace Personal,,,
1,None,FECHA DESCRIPCIÓN / ESTABLECIMIENTO MONTO DEL ...,,,
2,03-FEB-24,SALDO ANTERIOR,,,157.39
3,06-FEB-24,TRASP FONDOS 0000240206 AL R.F.C. CENE7504044...,,,137.39
4,None,Complemento IVA: . 0,,,
5,08-FEB-24,"TRASPASO 0000240208 , DE LA CUENTA: 1256031099",,700.00,837.39
6,08-FEB-24,TRASP FONDOS 0000240208 AL R.F.C. GOGC880322M...,,,57.39
7,None,Tratamientos IVA: . 0,,,
8,13-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"1,600.00",,"1,657.39"
9,None,MARIA FERNANDA CANUDAS ZERTUCHE en el cajero d...,,,
10,None,"LOC, MERIDA a las 10:52 hrs. - N70892",,,
11,15-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"4,050.00",,"5,707.39"
12,None,MARIA FERNANDA CANUDAS ZERTUCHE en el cajero d...,,,
13,None,hrs. - N71054,,,
14,15-FEB-24,"TRASPASO 0000240215 , DE LA CUENTA: 1256031099","3,801.50",,"9,508.89"
15,15-FEB-24,"2024021640014TRAP0000466719370 SPEI RECIBIDO,...",,500.00,"10,008.89"
16,None,DEL CLIENTE RODRIGO PUERTO BASSO DE LA CLABE 0...,,,
17,None,PUBR960828U82 CONCEPTO: TRANSFERENCIA A FER CA...,,,
18,None,CVE RAST: 2024021640014TRAP0000466719370,,,
19,15-FEB-24,CARGO POR PAGO CONCENTRACION MOV TARJETA DE C...,,,273.31
20,None,BMN930209927 RAS 38434046536436000165 FAC 000165,,,
21,19-FEB-24,FAR GUAD 2413 RFC:FGU 830930PD3,,,245.31
22,19-FEB-24,OXXO COCOYOLES MID RFC:CCO 8605231N4,,,140.31
23,19-FEB-24,MERPAGO*MARKET TP RFC:MAG 2105031W3,,,53.31
24,27-FEB-24,COMPRA ORDEN DE PAGO SPEI 0240227 =REFERENCIA...,,,19.31
25,None,BCO:137 BENEF:Alejandra Soli (DATO NO VERIF PO...,,,
26,None,3843CP04202402272880746719 RFC: No capturado I...,,,
27,28-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"7,500.00",,"7,519.31"
28,None,MARIA FERNANDA CANUDAS ZERTUCHE en el cajero d...,,,
29,None,"CE, MERIDA a las 18:22 hrs. - N70894",,,
30,01-MAR-24,VS TELCEL 018001200006 RFC:VPS 100716CK9,,,"7,070.31"
31,01-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240301 =REFERENCIA...,,,"6,870.31"
32,None,BCO:012 BENEF:NO INGRESAD (DATO NO VERIF POR E...,,,
33,None,3843CP03202403012889122723 RFC: No capturado I...,,,
34,02-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240302 =REFERENCIA...,,,"6,802.31"
35,None,BCO:137 BENEF:Alejandra Soli (DATO NO VERIF PO...,,,
36,None,3843CP05202403022893592470 RFC: No capturado I...,,,
37,04-MAR-24,LE CAFE 6 RFC:MCM 2207216Y1,,,"6,761.31"
38,04-MAR-24,MERPAGO*MARKET TP RFC:MAG 2105031W3,,,"6,679.31"
39,04-MAR-24,"MBAN01002403040069805037 SPEI RECIBIDO, BCO:0...","2,550.00",,"9,229.31"
40,None,CLIENTE ABIGAIL ZERTUCHE AVILA DE LA CLABE 012...,,,
41,None,CONCEPTO: super REFERENCIA: 0403240 CVE RAST: ...,,,
42,04-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240304 =REFERENCIA...,,,"4,695.10"
43,None,SPEI BCO:059 BENEF:NO INGRESAD (DATO NO VERIF ...,,,
44,None,3843CP04202403042896735209 RFC: No capturado I...,,,
45,04-MAR-24,Deposito en efectivo en cajero Banorte. Te de...,"3,000.00",,"7,695.10"
46,None,MARIA FERNANDA CANUDAS ZERTUCHE en el cajero d...,,,
47,None,hrs. - N71054,,,
48,None,Inversión Enlace Personal,,,

In [37]:
reconstructed_table = table_processor.reconstruct_table()
reconstructed_table

,Date,Description,MONTO DEL DEPOSITO,MONTO DEL RETIRO,SALDO
0,03-FEB-24,SALDO ANTERIOR,,,157.39
1,06-FEB-24,TRASP FONDOS 0000240206 AL R.F.C. CENE7504044...,,,137.39
2,08-FEB-24,"TRASPASO 0000240208 , DE LA CUENTA: 1256031099",,700.00,837.39
3,08-FEB-24,TRASP FONDOS 0000240208 AL R.F.C. GOGC880322M...,,,57.39
4,13-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"1,600.00",,"1,657.39"
5,15-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"4,050.00",,"5,707.39"
6,15-FEB-24,"TRASPASO 0000240215 , DE LA CUENTA: 1256031099","3,801.50",,"9,508.89"
7,15-FEB-24,"2024021640014TRAP0000466719370 SPEI RECIBIDO,...",,500.00,"10,008.89"
8,15-FEB-24,CARGO POR PAGO CONCENTRACION MOV TARJETA DE C...,,,273.31
9,19-FEB-24,FAR GUAD 2413 RFC:FGU 830930PD3,,,245.31
10,19-FEB-24,OXXO COCOYOLES MID RFC:CCO 8605231N4,,,140.31
11,19-FEB-24,MERPAGO*MARKET TP RFC:MAG 2105031W3,,,53.31
12,27-FEB-24,COMPRA ORDEN DE PAGO SPEI 0240227 =REFERENCIA...,,,19.31
13,28-FEB-24,Deposito en efectivo en cajero Banorte. Te de...,"7,500.00",,"7,519.31"
14,01-MAR-24,VS TELCEL 018001200006 RFC:VPS 100716CK9,,,"7,070.31"
15,01-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240301 =REFERENCIA...,,,"6,870.31"
16,02-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240302 =REFERENCIA...,,,"6,802.31"
17,04-MAR-24,LE CAFE 6 RFC:MCM 2207216Y1,,,"6,761.31"
18,04-MAR-24,MERPAGO*MARKET TP RFC:MAG 2105031W3,,,"6,679.31"
19,04-MAR-24,"MBAN01002403040069805037 SPEI RECIBIDO, BCO:0...","2,550.00",,"9,229.31"
20,04-MAR-24,COMPRA ORDEN DE PAGO SPEI 0240304 =REFERENCIA...,,,"4,695.10"
21,04-MAR-24,Deposito en efectivo en cajero Banorte. Te de...,"3,000.00",,"7,695.10"

In [38]:
if statement_type == 'debit':
    reconstructed_table_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_reconstructed_table.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    reconstructed_table_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_reconstructed_table.csv')
    
reconstructed_table.to_csv(reconstructed_table_path, index=False)

In [39]:
from models import DataProcessingFacade

data_processor = DataProcessingFacade(corrected_extracted_words, reconstructed_table, statement_properties)
df_transactions = data_processor.get_normalized_table()
df_transactions

,Date,Description,Amount,Type
0,2024-02-03,SALDO ANTERIOR,157.39,Saldo Inicial
1,2024-02-06,TRASP FONDOS 0000240206 AL R.F.C. CENE7504044...,137.39,Saldo
2,2024-02-08,"TRASPASO 0000240208 , DE LA CUENTA: 1256031099",-700.00,Cargo
3,2024-02-08,TRASP FONDOS 0000240208 AL R.F.C. GOGC880322M...,57.39,Saldo
4,2024-02-13,Deposito en efectivo en cajero Banorte. Te de...,1600.00,Abono
5,2024-02-15,Deposito en efectivo en cajero Banorte. Te de...,4050.00,Abono
6,2024-02-15,"TRASPASO 0000240215 , DE LA CUENTA: 1256031099",3801.50,Abono
7,2024-02-15,"2024021640014TRAP0000466719370 SPEI RECIBIDO,...",-500.00,Cargo
8,2024-02-15,CARGO POR PAGO CONCENTRACION MOV TARJETA DE C...,273.31,Saldo
11,2024-02-19,MERPAGO*MARKET TP RFC:MAG 2105031W3,53.31,Saldo
10,2024-02-19,OXXO COCOYOLES MID RFC:CCO 8605231N4,140.31,Saldo
9,2024-02-19,FAR GUAD 2413 RFC:FGU 830930PD3,245.31,Saldo
12,2024-02-27,COMPRA ORDEN DE PAGO SPEI 0240227 =REFERENCIA...,19.31,Saldo
13,2024-02-28,Deposito en efectivo en cajero Banorte. Te de...,7500.00,Abono
14,2024-03-01,VS TELCEL 018001200006 RFC:VPS 100716CK9,7070.31,Saldo
15,2024-03-01,COMPRA ORDEN DE PAGO SPEI 0240301 =REFERENCIA...,6870.31,Saldo
16,2024-03-02,COMPRA ORDEN DE PAGO SPEI 0240302 =REFERENCIA...,6802.31,Saldo
17,2024-03-04,LE CAFE 6 RFC:MCM 2207216Y1,6761.31,Saldo
18,2024-03-04,MERPAGO*MARKET TP RFC:MAG 2105031W3,6679.31,Saldo
19,2024-03-04,"MBAN01002403040069805037 SPEI RECIBIDO, BCO:0...",2550.00,Abono
20,2024-03-04,COMPRA ORDEN DE PAGO SPEI 0240304 =REFERENCIA...,4695.10,Saldo
21,2024-03-04,Deposito en efectivo en cajero Banorte. Te de...,3000.00,Abono

In [40]:
from models import CsvExporter

exporter = CsvExporter(df_transactions)
if statement_type == 'debit':
    normalized_table_path = os.path.join(OUTPUTS_FOLDER, f'{bank}_{statement_type}_normalized_table.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    normalized_table_path = os.path.join(OUTPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_normalized_table.csv')

exporter.export_data(normalized_table_path)